In [2]:
# setting up environnment
import pandas as pd

In [7]:
all_data = pd.read_csv("./Data/Data2016.csv", index_col=0)
all_data.index = pd.to_datetime(all_data.index)
display(all_data)

World Equities  10-year US Treasuries  High Yield  \
Date                                                            
1995-01-01       -0.020349               0.022922    0.032048   
1995-02-01        0.010680               0.030014    0.013531   
1995-03-01        0.045804               0.007195    0.025871   
1995-04-01        0.036372               0.016973    0.030836   
1995-05-01        0.011040               0.054900    0.006743   
...                    ...                    ...         ...   
2016-02-01             NaN                    NaN    0.044208   
2016-03-01             NaN                    NaN    0.039953   
2016-04-01             NaN                    NaN    0.007221   
2016-05-01             NaN                    NaN    0.010833   
2016-06-01             NaN                    NaN    0.025964   

            Inflation Protection  Currency Protection  U.S. Equity  \
Date                                                                 
1995-01-01              0.006524            -0.003404     0.022239   
1995-02-01             -0.038375            -0.020587     0.036258   
1995-03-01             -0.023184            -0.042060     0.030791   
1995-04-01             -0.003600            -0.015827     0.022403   
1995-05-01             -0.054282             0.009121     0.036521   
...                          ...                  ...          ...   
2016-02-01                   NaN            -0.023402     0.023712   
2016-03-01                   NaN            -0.037563     0.051944   
2016-04-01                   NaN            -0.020016     0.008720   
2016-05-01                   NaN             0.033049     0.011779   
2016-06-01                   NaN            -0.003491     0.003738   

            SP500 Total Return   S&P 500  International Equity  \
Date                                                             
1995-01-01            0.025954  0.025897             -0.039228   
1995-02-01            0.035540  0.038974             -0.000434   
1995-03-01            0.035454  0.029502              0.061949   
1995-04-01            0.026256  0.029414              0.037154   
1995-05-01            0.040894  0.039949             -0.009769   
...                        ...       ...                   ...   
2016-02-01            0.022927       NaN             -0.011061   
2016-03-01            0.049537       NaN              0.036116   
2016-04-01            0.005354       NaN              0.051411   
2016-05-01            0.011375       NaN             -0.010807   
2016-06-01            0.003426       NaN             -0.018297   

            U.S. Treasury 20 years  Corporate Bond  Real Estate  Commodity  \
Date                                                                         
1995-01-01                0.025987        0.017042    -0.014847  -0.023908   
1995-02-01                0.026960        0.029870     0.032460   0.002221   
1995-03-01                0.009477        0.011937    -0.005961   0.019558   
1995-04-01                0.017695        0.010995     0.002259   0.038085   
1995-05-01                0.076715        0.053217     0.045025  -0.009417   
...                            ...             ...          ...        ...   
2016-02-01                0.028198        0.006360     0.021567   0.009421   
2016-03-01                0.001023        0.030894     0.072566   0.022858   
2016-04-01                     NaN        0.011063    -0.002171   0.109346   
2016-05-01                     NaN        0.001398     0.009775   0.039373   
2016-06-01                     NaN        0.025798     0.066622   0.005294   

                TIPS  
Date                  
1995-01-01  0.029446  
1995-02-01 -0.008361  
1995-03-01 -0.015989  
1995-04-01  0.013373  
1995-05-01  0.000618  
...              ...  
2016-02-01       NaN  
2016-03-01       NaN  
2016-04-01       NaN  
2016-05-01       NaN  
2016-06-01       NaN  

[258 rows x 14 columns]

In [11]:
pd.options.display.float_format = "{:, 3f}.format"
all_data.sort_values('SP500 Total Return', ascending=False).head(3)

World Equities  10-year US Treasuries  High Yield  \
Date                                                            
2009-03-01        0.157022               0.032915    0.114651   
1998-10-01        0.091328              -0.010324    0.051874   
2011-10-01        0.099737              -0.012101   -0.022108   

            Inflation Protection  Currency Protection  U.S. Equity  \
Date                                                                 
2009-03-01              0.025554            -0.022223     0.160889   
1998-10-01              0.012481            -0.034959     0.125694   
2011-10-01              0.030714            -0.032055     0.117158   

            SP500 Total Return   S&P 500  International Equity  \
Date                                                             
2009-03-01            0.159867  0.087591              0.140610   
1998-10-01            0.128015  0.081331              0.104403   
2011-10-01            0.109822  0.109293              0.076465   

            U.S. Treasury 20 years  Corporate Bond  Real Estate  Commodity  \
Date                                                                         
2009-03-01                0.057347       -0.002966     0.117361   0.097293   
1998-10-01               -0.021293       -0.024602    -0.027235  -0.029296   
2011-10-01               -0.022895        0.017495     0.148804   0.096833   

                TIPS  
Date                  
2009-03-01  0.058469  
1998-10-01  0.002157  
2011-10-01  0.018613

In [13]:
# Linear regression via SciKit-Learn
import sklearn

In [10]:
import cvxpy as cp
import numpy as np

# Problem data.
m = 30
n = 3
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A @ x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)

[ 2.75372707e-01 -1.98451768e-20  4.97551483e-02]
[0.         2.32318387 0.        ]


In [3]:
A

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ]])

In [4]:
b

array([ 1.74481176, -0.7612069 ,  0.3190391 ])

In [5]:
x

Variable((2,), var45)

In [6]:
objective

Minimize(Expression(CONVEX, NONNEGATIVE, ()))